In [ ]:
import pandas as pd

dataset = pd.read_csv("/content/drive/MyDrive/College Materials/Datasets Python/Titanic-Dataset.csv")

## **Problem 1 - Sorting:**
1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.
2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.
3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.

In [ ]:
#1
fare = dataset[["Fare"]]
fare.head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

In [ ]:
#2
class_age = dataset[["Pclass", "Age"]]
class_age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

In [ ]:
#3
survived_gender = dataset[["Survived", "Sex"]]
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

# **Problem - 2 - Subsetting:**
Complete all the following Task:
Subsetting Rows:
1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.
2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.
3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.

In [ ]:
#1
fare_gt_100 = dataset[dataset["Fare"] > 100]
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [ ]:
#2
first_class = dataset[dataset['Pclass'] == 1]
first_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [ ]:
#3
female_under_18 = dataset[(dataset['Age'] < 18) & (dataset['Sex'] == 'female')]
female_under_18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

**Subsetting Rows by Categorical variables:**
1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.
2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.

Subsetting Rows by Categorical variables:
1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.
2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.

In [ ]:
embarked_c_or_s = dataset[(dataset['Embarked'] == 'C') | (dataset['Embarked'] == 'S')]
embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
first_second_class = dataset[dataset['Pclass'].isin([1, 2])]
first_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

# **3.2 Exploratory Data Analysis Practice Exercise - 1.**
Warning: Handle missing values in the Age column by filling them with the median age of the dataset before performing the division.

Answer the following questions from Dataset:

**Which passenger had the highest fare paid relative to their age?**

To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).
2. Subset rows where fare per year is higher than 5, assigning this to high fare age.
3. Sort high fare age by descending fare per year, assigning this to high fare age srt.
4. Select only the Name and fare per year columns of high fare age srt and save the result as result.
5. Look at the result.

In [ ]:
dataset['Age'].fillna(dataset['Age'].median(), inplace=True)
dataset['fare_per_year'] = dataset['Fare'] / dataset['Age']

high_fare_age = dataset[dataset['fare_per_year'] > 5]

high_fare_age_srt = high_fare_age.sort_values(by=['fare_per_year'], ascending=False)

result = high_fare_age_srt[['Name', 'fare_per_year']]

result.head()

<ipython-input-19-d1cdbfdd319c>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Age'].fillna(dataset['Age'].median(), inplace=True)

                                Name  fare_per_year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

**Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?**

To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.
2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.
3. Sort adult males by descending fare per class, assigning this to adult males srt.
4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.

In [ ]:
dataset['fare_per_class'] = dataset['Fare'] / dataset['Pclass']

adult_males = dataset[(dataset['Sex'] == 'male') & (dataset['Age'] >= 18)]

adult_males_srt = adult_males.sort_values(by=['fare_per_class'], ascending=False)

result = adult_males_srt[['Name', 'Age', 'fare_per_class']]

result.head()

                                   Name   Age  fare_per_class
737              Lesurer, Mr. Gustave J  35.0        512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
438                   Fortune, Mr. Mark  64.0        263.0000
27       Fortune, Mr. Charles Alexander  19.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208

# **3.3 Exploratory Data Analysis with Group-by Method Practice Exercise:**
Based on the dataset Answer the following question:
What percent of the total fare revenue came from each passenger class?
To answer the question perform following operation:
1. Calculate the total Fare paid across all passengers in the Titanic dataset.
2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.
3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).
4. Combine the fare totals from first, second, and third classes into a list.
5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.

In [ ]:
total_fare = dataset['Fare'].sum()

first_class_fare = dataset[dataset['Pclass'] == 1]['Fare'].sum()

second_class_fare = dataset[dataset['Pclass'] == 2]['Fare'].sum()

third_class_fare = dataset[dataset['Pclass'] == 3]['Fare'].sum()

class_fares = [first_class_fare, second_class_fare, third_class_fare]

class_proportions = [fare / total_fare * 100 for fare in class_fares]

print("Percentage of total fare revenue by passenger class:")
print("First Class: {:.2f}%".format(class_proportions[0]))
print("Second Class: {:.2f}%".format(class_proportions[1]))
print("Third Class: {:.2f}%".format(class_proportions[2]))

Percentage of total fare revenue by passenger class:
First Class: 63.35%
Second Class: 13.25%
Third Class: 23.40%

Based on the dataset Answer the following question:

What percent of the total number of passengers on the Titanic belonged to each age group
(e.g., child, adult, senior)?
To answer the question perform following operation:
1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18{64), and "senior" (age 65 and above).
2. Calculate the total number of passengers on the Titanic.
3. Count the number of passengers in each age group.
4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.
5. Display the proportion as a percentage.

In [ ]:
dataset['age_group'] = pd.cut(dataset['Age'], bins=[0, 18, 65, float('inf')], labels=['child', 'adult', 'senior'])

total_passengers = len(dataset)

age_group_counts = dataset['age_group'].value_counts()

age_group_proportions = (age_group_counts / total_passengers) * 100

print("Percentage of passengers in each age group:")
print(age_group_proportions)

Percentage of passengers in each age group:
age_group
adult     83.501684
child     15.600449
senior     0.897868
Name: count, dtype: float64